checks:
  golint:
    filters:
      - value: "should have comment or be unexported"
      - value: "or a comment on this block"
    exclude:
      paths: []
  deadcode:
    exclude:
      paths: []
  varcheck:
    exclude:
      paths: []
  importalias:
    exclude:
      paths: []
