name: 🎉 Release Binary

on:
  push:
    tags:
      - v*

permissions:
  id-token: write # For cosign
  packages: write # For GHCR
  contents: write # To upload archives as release assets

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.26"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release -f .goreleaser.yaml --clean
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
