name: 🔨 Release Test

on:
  workflow_call:
  pull_request:
    paths:
      - "**/*"
  push:
    branches:
      - develop
jobs:
  release-test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.26"

      - name: release test
        uses: goreleaser/goreleaser-action@v4
        with:
          args: "release --clean --snapshot -f .goreleaser.yaml"
          version: latest
